 spring:
     datasource:
         type: com.zaxxer.hikari.HikariDataSource        
         url: jdbc:mysql://${MYSQL_ADDON_HOST}:${MYSQL_ADDON_PORT}/${MYSQL_ADDON_DB}?useUnicode=true&characterEncoding=utf8&useSSL=false
         username: ${MYSQL_ADDON_USER}
         password: ${MYSQL_ADDON_PASSWORD}
         hikari:
             maximumPoolSize: 2